Feature/more generic wait
PGSSoft/AutoMate pull request #4
Opened 2017-03-17 21:40 UTC by mmysliwiec

Added more generic `wait(forFulfillmentOf...)` method. Existing `wait(...)` methods are using this new method now.
Added `wait(forInvisibilityOf...)` method for waiting until the element disappear.

2017-03-18 07:47 UTC, bartoszj requested changes
Update Changelog.md ;)

2017-03-18 20:28 UTC, bartoszj approved these changes

2017-03-20 07:54 UTC, dzoanb commented on AutoMate/XCTest extensions/XCTestCase.swift
> +                     withFailingMessage message: String = "Failed to fulfill predicate %@ for %@ within %.2f seconds.",
What do You think about `@autoclosure` like in `XCAsserts`?

2017-03-20 08:02 UTC, dzoanb approved these changes

2017-03-21 06:26 UTC, merged